name = "v2-xbot"
compatibility_date = "2023-01-01"
node_compat = true
vars = { env = "staging", enableLog = "false", botToken = "YOUR_BOT_TOKEN", adminId = "YOUR_ADMIN_ID", tlgSupport = "@YOUR_SUUPORT_ID" }
kv_namespaces = [
    { binding = "db", id = "YOUR_KV_ID" },
]
[triggers]
crons = ["0 */1 * * *"] # Auto-Backup cron job

